version: '3'
services:
  node_app:
    build: .
    volumes:
      - ./:/app:ro
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  mongo:
    image: mongo 
    volumes:
      - mongo_db:/data/db
    
volumes:
  mongo_db: